// Re-export environment configuration from generated environment.ts
// The environment.ts file is auto-generated by scripts/generate-env.js
// which reads values from the .env file
//
// To change configuration:
// 1. Edit the .env file in the project root
// 2. Run: npm run generate-env (or just npm start - it runs automatically)

export * from '../../environments/environment';
